#!/bin/sh
# .git/hooks/pre-commit

echo "Running cargo fmt --check..."
cargo fmt -- --check
if [ $? -ne 0 ]; then
    echo "Formatting check failed. Run 'cargo fmt' to fix."
    exit 1
fi

echo "Running cargo clippy..."
cargo clippy --all-targets --all-features -- -D warnings
if [ $? -ne 0 ]; then
    echo "Clippy check failed. Fix warnings before committing."
    exit 1
fi


echo "Running cargo deny check..."
cargo deny check licenses
if [ $? -ne 0 ]; then
    echo "License check failed."
    exit 1
fi

echo "Checks passed!"
exit 0
