#!/bin/bash
set -e

echo "======================================"
echo " AWS Profile Manager (awspm)"
echo " Dependency Upgrade & Verification Automation"
echo "======================================"

# 実行モードの確認
MODE="update"
AUTO_COMMIT=false
CREATE_PR=false

for arg in "$@"; do
    case $arg in
        --major)
            MODE="upgrade"
            ;;
        --commit)
            AUTO_COMMIT=true
            ;;
        --pr)
            CREATE_PR=true
            AUTO_COMMIT=true
            ;;
    esac
done

if [ "$MODE" == "upgrade" ]; then
    echo "[Step 1] Running Major Upgrade (cargo upgrade)..."
    mise exec -- cargo upgrade --exclude clap --exclude clap_complete --exclude tempfile
else
    echo "[Step 1] Running Safe Update (cargo update)..."
    mise exec -- cargo update
fi

echo ""
echo "[Step 2] Checking Formatting and Linting..."
mise exec -- cargo fmt --all
mise exec -- cargo clippy --all-targets --all-features -- -D warnings
echo "✅ Lint & Format passed."

echo ""
echo "[Step 3] Running Unit and Integration Tests..."
mise exec -- cargo test
echo "✅ Unit & Integration Tests passed."

echo ""
echo "[Step 4] Running End-to-End Tests..."
if [ -f "./e2e_test.sh" ]; then
    ./e2e_test.sh
else
    echo "⚠️ ./e2e_test.sh not found. Skipping."
fi
echo "✅ E2E Tests passed."

echo ""
echo "[Step 5] Regenerating Third-Party Licenses..."
mise exec -- cargo about generate about.hbs > THIRD_PARTY_LICENSES.md
echo "✅ THIRD_PARTY_LICENSES.md regenerated."

echo ""
echo "[Step 6] Running Security and License Audit (cargo deny)..."
mise exec -- cargo deny check
echo "✅ Security & License audit passed."

echo ""
if [ "$AUTO_COMMIT" = true ]; then
    echo "[Step 7] Auto-committing and Updating CHANGELOG..."
    git add Cargo.toml Cargo.lock THIRD_PARTY_LICENSES.md
    if [ "$MODE" == "upgrade" ]; then
        git commit -m "chore: upgrade major dependencies"
    else
        git commit -m "chore: update dependencies"
    fi
    # コミット履歴を元にCHANGELOGへ追記
    mise exec -- git cliff --unreleased --prepend CHANGELOG.md
    git add CHANGELOG.md
    git commit --amend --no-edit
    echo "✅ Changes committed and CHANGELOG.md updated!"
fi

if [ "$CREATE_PR" = true ]; then
    echo ""
    echo "[Step 8] Creating Pull Request..."
    if ! command -v gh &> /dev/null; then
        echo "❌ Error: 'gh' command not found. Please install GitHub CLI to create PRs automatically."
        exit 1
    fi

    BRANCH_NAME=$(git branch --show-current)
    if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
        echo "❌ Error: You are on the main/master branch. Please create a new branch before running with --pr."
        exit 1
    fi

    echo "Pushing branch $BRANCH_NAME to origin..."
    git push -u origin "$BRANCH_NAME"

    if [ "$MODE" == "upgrade" ]; then
        PR_TITLE="chore: upgrade major dependencies"
    else
        PR_TITLE="chore: update dependencies"
    fi

    PR_BODY_FILE=$(mktemp)
    TEMPLATE_FILE=".github/PULL_REQUEST_TEMPLATE.md"
    if [ -f "$TEMPLATE_FILE" ]; then
        # PRテンプレートを読み込み、Descriptionの部分を自動生成テキストに置換
        cat "$TEMPLATE_FILE" | \
            sed 's/<!-- A clear and concise description of what this PR does. -->/Automated dependency updates generated by `scripts\/upgrade_deps.sh`./' | \
            sed 's/- \[ \] 🏗️ Refactoring (no functional changes, no api changes)/- [x] 🏗️ Refactoring (no functional changes, no api changes)/' > "$PR_BODY_FILE"
    else
        echo "Automated dependency updates." > "$PR_BODY_FILE"
    fi

    gh pr create --title "$PR_TITLE" --body-file "$PR_BODY_FILE"
    rm -f "$PR_BODY_FILE"
    echo "✅ Pull Request created successfully!"
fi

if [ "$AUTO_COMMIT" = false ] && [ "$CREATE_PR" = false ]; then
    echo ""
    echo "🎉 All checks completed successfully!"
    echo "To automatically commit and update CHANGELOG.md, run with '--commit' flag."
    echo "To automatically commit and create a Pull Request, run with '--pr' flag."
    if [ "$MODE" == "update" ]; then
        echo "Run './scripts/upgrade_deps.sh --major' to perform a major version upgrade."
    fi
fi
